Commiting Patrick's change on the right branch
WildCodeSchool/Sugar-rush-project-sugar-rush pull request #20
Opened 2023-06-22 15:38 UTC by FlorianHe

2023-06-22 16:59 UTC, SelinGitt submitted a review, later dismissed

2023-06-23 08:12 UTC, Benja-san requested changes

2023-06-23 08:12 UTC, Benja-san commented on src/app/header/header.component.html
> +            <ul id="smallscr">
This one should be present only if device has smallScreen size

2023-06-23 08:12 UTC, Benja-san commented on src/app/header/header.component.html
> +            <ul id="smallscr">
Visibility hidden and duplicate content is not a good practice

2023-06-23 08:52 UTC, SelinGitt approved these changes

2023-06-23 08:59 UTC, Benja-san approved these changes

2023-06-23 09:00 UTC, merged