Us s3 recette
WildCodeSchool/Sugar-rush-project-sugar-rush pull request #28
Opened 2023-07-10 11:52 UTC by FlorianHe

Mise à jour css du projet après le 3ème sprint

2023-07-11 11:47 UTC, alexboutemy approved these changes

2023-07-12 07:30 UTC, Benja-san requested changes

2023-07-12 07:30 UTC, Benja-san commented on src/app/app.component.scss
>        /* Center the element horizontally */
dead code

2023-07-12 07:30 UTC, Benja-san commented on src/styles.scss
>  // Alternatively, you can import and @include the theme mixins for each component
dead code ?

2023-07-12 08:38 UTC, alexboutemy approved these changes

2023-07-12 08:45 UTC, Benja-san approved these changes

2023-07-12 09:11 UTC, merged