Us interfaces
WildCodeSchool/Sugar-rush-project-sugar-rush pull request #6
Opened 2023-06-15 13:26 UTC by FlorianHe

Adding interfaces and prepared datas to use while waiting for the back to be develop

2023-06-15 14:01 UTC, Guillaum6e submitted a review, later dismissed

2023-06-16 08:33 UTC, Guillaum6e approved these changes

2023-06-16 09:51 UTC, Benja-san requested changes

2023-06-16 09:51 UTC, Benja-san commented on src/app/shared/datas/article.ts
> +    "title": "Le caramel qui colle aux dents : pour ou contre ?",
add a slug entry for better url navigation with slug

2023-06-16 09:51 UTC, Benja-san commented on src/app/shared/datas/articles.ts
> +    "title": "Le caramel qui colle aux dents : pour ou contre ?",
use slug entry for better navigation. eg: slug: "le-caramel-qui-colle-aux-dents-pour-ou-contre"

2023-06-16 09:51 UTC, Benja-san commented on src/app/shared/datas/categories.ts
> +        "name" : "Fun"
use slug entry as well for url navigation

2023-06-16 09:51 UTC, Benja-san commented on src/app/shared/interfaces/article.ts
> +    title: string
add slug property

2023-06-16 09:51 UTC, Benja-san commented on src/app/shared/interfaces/category.ts
> +    name : string
add slug property

2023-06-16 10:15 UTC, Benja-san approved these changes

2023-06-16 10:16 UTC, Guillaum6e approved these changes

2023-06-16 10:17 UTC, merged